// A página é autocontida para operar offline, sem build nem dependências remotas.
export const PAGE_M7Q = `<!doctype html>
<html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>localWorker · jobs</title><style>
:root{color-scheme:dark;--bg:#0c111b;--panel:#151e2c;--panel2:#1b2839;--line:#2b3a50;--text:#e9f0fb;--muted:#a8b7ca;--accent:#77b9ff;--good:#78d8ad;--warn:#f3c77d;--bad:#ff8f95}
*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at top right,#1a3150 0,transparent 32rem),var(--bg);color:var(--text);font:15px/1.5 system-ui,-apple-system,"Segoe UI",sans-serif}
main{max-width:1200px;margin:0 auto;padding:28px 22px 60px}header{display:flex;justify-content:space-between;align-items:flex-end;gap:16px;border-bottom:1px solid var(--line);padding-bottom:18px}h1{font-size:1.8rem;line-height:1.15;margin:0}h2{font-size:1.15rem;margin:26px 0 12px}p{margin:8px 0}.eyebrow{color:var(--accent);font-size:.78rem;text-transform:uppercase;letter-spacing:.12em;font-weight:700}.muted,small{color:var(--muted)}a{color:var(--accent);text-decoration:none}a:hover{text-decoration:underline}.brand{display:flex;align-items:center;gap:13px}.mark{width:36px;height:36px;border-radius:10px;background:linear-gradient(135deg,#54a9f7,#4c76d7);display:grid;place-items:center;color:#07121e;font-weight:900}
.shell{margin-top:22px}.cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(175px,1fr));gap:12px}.card{background:var(--panel);border:1px solid var(--line);border-radius:12px;padding:15px 16px;min-width:0}.card small{display:block;margin-bottom:4px}.card strong{font-size:1.08rem;overflow-wrap:anywhere;font-weight:650}.panel{background:var(--panel);border:1px solid var(--line);border-radius:14px;margin-top:18px;overflow:hidden}.panelhead{padding:17px 18px;border-bottom:1px solid var(--line);display:flex;align-items:center;justify-content:space-between;gap:12px;flex-wrap:wrap}.panelhead h2{margin:0}.controls{display:flex;gap:10px;flex-wrap:wrap;padding:16px 18px}.control{display:flex;flex-direction:column;gap:4px;min-width:145px;flex:1}.control.wide{flex:2;min-width:220px}.control label{color:var(--muted);font-size:.78rem}select,button{font:inherit;background:var(--panel2);color:var(--text);border:1px solid var(--line);border-radius:8px;padding:8px 10px}button{cursor:pointer}button:hover,select:focus{border-color:var(--accent)}button:disabled{opacity:.45;cursor:default}.tablewrap{overflow:auto}table{width:100%;border-collapse:collapse}th,td{text-align:left;vertical-align:top;padding:12px 16px;border-top:1px solid var(--line)}th{color:var(--muted);font-size:.78rem;font-weight:650;white-space:nowrap}td{overflow-wrap:anywhere}tr:hover td{background:#1b293b}.mono{font-family:ui-monospace,SFMono-Regular,Consolas,monospace;font-size:.82rem}.pill{display:inline-block;border-radius:999px;padding:2px 9px;background:#2b425e;color:var(--accent);font-size:.77rem;font-weight:650;white-space:nowrap}.pill.COMPLETED{background:#173d34;color:var(--good)}.pill.FAILED,.pill.CANCELLED{background:#503038;color:var(--bad)}.pill.RUNNING{background:#3d3825;color:var(--warn)}.task{max-width:370px;white-space:pre-wrap}.repo{max-width:260px;color:var(--muted);font-size:.84rem}.pager{display:flex;align-items:center;justify-content:flex-end;gap:10px;padding:14px 18px;border-top:1px solid var(--line)}.diagnostic{white-space:pre-wrap;overflow-wrap:anywhere;color:var(--muted);padding:16px 18px;margin:0}.empty{padding:26px;color:var(--muted)}.sectionlink{font-size:.86rem}.subtitle{max-width:760px;color:var(--muted)}.metric{font-size:.85rem;color:var(--muted)}
.job-action{width:38px;height:38px;padding:0;display:inline-grid;place-items:center;font-size:1.1rem}.job-action.stop{color:var(--warn)}.job-action.delete{color:var(--bad)}.job-spinner{width:19px;height:19px;border:2px solid var(--line);border-top-color:var(--accent);border-radius:50%;animation:job-spin .7s linear infinite}@keyframes job-spin{to{transform:rotate(360deg)}}.job-notice{position:fixed;right:18px;bottom:18px;max-width:min(420px,calc(100vw - 36px));padding:12px 16px;border-radius:10px;background:#503038;box-shadow:0 10px 30px #0008;z-index:5}
@media(max-width:650px){main{padding:18px 12px 45px}header{align-items:flex-start}h1{font-size:1.45rem}th,td{padding:10px}.cards{grid-template-columns:repeat(2,minmax(0,1fr))}.repo{max-width:160px}}
</style></head><body><main><header><div><div class="brand"><div class="mark">W</div><div><div class="eyebrow">Acompanhamento local</div><h1>localWorker</h1></div></div><p class="subtitle">Jobs persistidos nesta máquina. Fechar esta página não interrompe a execução; os dados se atualizam automaticamente.</p></div><a id="homeLink" class="sectionlink" href="#">Todos os jobs ↗</a></header>
<section id="index" class="shell" hidden><div class="cards"><div class="card"><small>Jobs retidos</small><strong id="allTotal">—</strong></div><div class="card"><small>Resultado do filtro</small><strong id="filterTotal">—</strong></div><div class="card"><small>Atualizado</small><strong id="indexObserved">—</strong></div></div><div class="panel"><div class="panelhead"><h2>Solicitações</h2><span class="muted">Repositório Git como agrupamento disponível</span></div><div class="controls"><div class="control wide"><label for="repoFilter">Repositório</label><select id="repoFilter"></select></div><div class="control"><label for="statusFilter">Status</label><select id="statusFilter"></select></div><div class="control"><label for="sortField">Ordenar por</label><select id="sortField"><option value="time">Tempo</option><option value="status">Status</option></select></div><div class="control"><label for="sortDirection">Direção</label><select id="sortDirection"><option value="desc">Decrescente</option><option value="asc">Crescente</option></select></div></div><div class="tablewrap"><table><thead><tr><th>Início</th><th>Status</th><th>Solicitação</th><th>Repositório</th><th>Duração</th><th>Entrega</th></tr></thead><tbody id="jobs"></tbody></table></div><div class="pager"><span id="pageInfo" class="muted"></span><button id="prev">Anterior</button><button id="next">Próxima</button></div></div></section>
<section id="detail" class="shell" hidden><div class="cards"><div class="card"><small>Status</small><strong id="status">—</strong></div><div class="card"><small>Atividade</small><strong id="activity">—</strong></div><div class="card"><small>Duração</small><strong id="duration">—</strong></div><div class="card"><small>Progresso</small><strong id="step">—</strong></div><div class="card"><small>Entrega ao chat</small><strong id="delivery">—</strong></div><div class="card"><small>Tokens entrada / saída</small><strong id="tokens">—</strong></div></div><div class="panel"><div class="panelhead"><h2>Diagnóstico</h2><span id="jobId" class="mono muted"></span></div><p id="request" class="diagnostic"></p><p id="reason" class="diagnostic"></p><p id="resources" class="diagnostic"></p><p id="metrics" class="diagnostic"></p></div><div class="panel"><div class="panelhead"><h2>Timeline do Worker</h2><span class="muted">Eventos operacionais em ordem cronológica; sem raciocínio privado</span></div><div class="tablewrap"><table><thead><tr><th>Horário</th><th>Etapa / ação</th><th>Recurso, decisão, resultado ou erro</th></tr></thead><tbody id="events"></tbody></table></div></div></section>
</main><script>
const token=new URLSearchParams(location.search).get('token')||'',id=/^\\/job\\/([0-9a-f-]{36})$/i.exec(location.pathname)?.[1]||null;
const PAGE_LIMIT_M7Q=50,DETAIL_REFRESH_MS_M7Q=3000,INDEX_REFRESH_MS_M7Q=10000;
const byId=name=>document.getElementById(name),put=(name,value)=>byId(name).textContent=String(value??'—');
const fmtDate=value=>value?new Date(value).toLocaleString('pt-BR'): '—';
const fmtDuration=value=>{if(!Number.isFinite(value))return '—';const s=Math.max(0,Math.floor(value/1000));return [Math.floor(s/3600),Math.floor(s/60)%60,s%60].map(n=>String(n).padStart(2,'0')).join(':')};
const metric=value=>value==null?'indisponível':String(value);
const link=(job)=>'/job/'+encodeURIComponent(job)+'?token='+encodeURIComponent(token);
byId('homeLink').href='/?token='+encodeURIComponent(token);byId(id?'detail':'index').hidden=false;byId('homeLink').hidden=!id;
let offset=0,lastEvents='',updating=false;
const filters=['repoFilter','statusFilter','sortField','sortDirection'];
for(const name of filters)byId(name).addEventListener('change',()=>{offset=0;void update()});
byId('prev').addEventListener('click',()=>{offset=Math.max(0,offset-PAGE_LIMIT_M7Q);void update()});
byId('next').addEventListener('click',()=>{offset+=PAGE_LIMIT_M7Q;void update()});
function options(name,values,allLabel){const select=byId(name),current=select.value;select.replaceChildren();const all=document.createElement('option');all.value='';all.textContent=allLabel;select.append(all);for(const value of values){const option=document.createElement('option');option.value=value;option.textContent=value;select.append(option)}select.value=values.includes(current)?current:''}
async function api(route){const response=await fetch(route+(route.includes('?')?'&':'?')+'token='+encodeURIComponent(token),{cache:'no-store'});if(!response.ok)throw Error('HTTP '+response.status);return response.json()}
async function updateIndex(){const params=new URLSearchParams({repo:byId('repoFilter').value,status:byId('statusFilter').value,sort:byId('sortField').value,direction:byId('sortDirection').value,offset:String(offset),limit:String(PAGE_LIMIT_M7Q)});const x=await api('/api/jobs?'+params);options('repoFilter',x.repositories,'Todos os repositórios');options('statusFilter',x.statuses,'Todos os status');put('allTotal',x.all_total);put('filterTotal',x.total);put('indexObserved',fmtDate(x.observed_at));const body=byId('jobs');body.replaceChildren();for(const job of x.jobs){const tr=document.createElement('tr');const cells=[fmtDate(job.created_at),job.status,job.task||'—',job.repo,fmtDuration(job.duration_ms),job.delivery];for(let i=0;i<cells.length;i++){const td=document.createElement('td');if(i===1){const badge=document.createElement('span');badge.className='pill '+job.status;badge.textContent=cells[i];td.append(badge)}else if(i===2){const a=document.createElement('a');a.href=link(job.job_id);a.textContent=cells[i];a.className='task';td.append(a)}else{td.textContent=cells[i];if(i===3)td.className='repo';if(i===0)td.className='mono'}tr.append(td)}body.append(tr)}if(!x.jobs.length){const tr=document.createElement('tr'),td=document.createElement('td');td.colSpan=6;td.className='empty';td.textContent='Nenhum job corresponde ao filtro.';tr.append(td);body.append(tr)}put('pageInfo',x.total?((offset+1)+'–'+Math.min(offset+x.jobs.length,x.total)+' de '+x.total):'0 de 0');byId('prev').disabled=offset===0;byId('next').disabled=offset+x.jobs.length>=x.total}
async function updateDetail(){const x=await api('/api/job/'+encodeURIComponent(id));const s=x.state,m=x.metrics,r=x.resource,p=x.progress;put('jobId',id);put('status',s.status);put('activity',x.activity.kind);put('duration',fmtDuration(x.duration_ms));put('step',p.step+'/'+p.max_steps+' ciclos · '+p.completed_tools+' ações concluídas · '+p.failed_tools+' falhas');put('delivery',x.delivery.status);put('tokens',metric(m.prompt_tokens_observed)+' / '+metric(m.output_tokens_observed));put('request',(x.request.task||'—')+'\\n'+(x.request.repoPath||'—')+' · '+(x.request.mode||'—'));put('reason',x.activity.reason+'\\nHeartbeat: '+(s.heartbeat_at||'—')+' · Observado: '+fmtDate(x.observed_at));put('resources','CPU Ollama: '+metric(r.ollama_cpu_seconds)+' s · RAM Ollama: '+(r.ollama_memory_bytes==null?'indisponível':Math.round(r.ollama_memory_bytes/1048576)+' MiB')+' · RAM livre: '+Math.round(r.ram_available_bytes/1048576)+' MiB\\nGPU: '+metric(r.gpu_percent)+'% · VRAM usada/livre: '+metric(r.gpu_used_mib)+' / '+metric(r.gpu_free_mib)+' MiB');put('metrics','Contexto configurado: '+metric(m.context_tokens_configured)+' tokens · geração observada: '+(m.generation_ms_observed/1000).toFixed(1)+' s\\n'+m.api_cost);const fingerprint=x.events.length+'|'+(x.events.at(-1)?.at||'');if(fingerprint!==lastEvents){lastEvents=fingerprint;const body=byId('events');body.replaceChildren();for(const event of x.events){const tr=document.createElement('tr');const cells=[fmtDate(event.at),event.phase+' '+(event.tool||''),[event.resource,event.outcome,event.reason,event.summary,event.error,event.diagnostic].filter(Boolean).join(' · ')];for(let i=0;i<cells.length;i++){const td=document.createElement('td');td.textContent=cells[i];if(i===0)td.className='mono';tr.append(td)}body.append(tr)}}}
async function update(){if(updating)return;updating=true;try{if(id)await updateDetail();else await updateIndex()}catch(error){put(id?'reason':'pageInfo','Monitor indisponível: '+error.message)}finally{updating=false}}
void update();setInterval(()=>{if(!document.hidden)void update()},id?DETAIL_REFRESH_MS_M7Q:INDEX_REFRESH_MS_M7Q);document.addEventListener('visibilitychange',()=>{if(!document.hidden)void update()});
</script><script>
(()=>{
const pending=new Set(),params=new URLSearchParams(location.search),key=params.get('token')||'';
const detailId=new RegExp('^/job/([0-9a-f-]{36})$','i').exec(location.pathname)?.[1]||null;
const notice=document.createElement('div');notice.className='job-notice';notice.setAttribute('role','alert');notice.hidden=true;document.body.append(notice);
function alertUser(message){notice.textContent=message;notice.hidden=false;setTimeout(()=>{if(notice.textContent===message)notice.hidden=true},7000)}
function action(jobId,status){const running=status==='RUNNING'||status==='QUEUED';const button=document.createElement('button');button.type='button';button.className='job-action '+(running?'stop':'delete');button.title=running?'Interromper este job':'Excluir definitivamente este job';button.setAttribute('aria-label',button.title);button.disabled=pending.has(jobId);if(button.disabled){const spinner=document.createElement('span');spinner.className='job-spinner';button.append(spinner)}else button.textContent=running?'■':'🗑';button.addEventListener('click',async()=>{
if(pending.has(jobId))return;if(!running&&!confirm('Excluir definitivamente todos os artefatos deste job?'))return;
pending.add(jobId);button.disabled=true;button.textContent='';const spinner=document.createElement('span');spinner.className='job-spinner';button.append(spinner);
try{const response=await fetch('/api/job/'+encodeURIComponent(jobId)+(running?'/cancel':'')+'?token='+encodeURIComponent(key),{method:running?'POST':'DELETE',cache:'no-store'});const result=await response.json();if(!response.ok||!result.confirmed)throw Error(result.error||'Estado real: '+result.status);if(!running&&detailId){location.href='/?token='+encodeURIComponent(key);return}if(!running){button.closest('tr')?.remove()}await update();}
catch(error){alertUser((running?'STOP':'Exclusão')+' falhou: '+error.message)}finally{pending.delete(jobId);button.disabled=false;button.textContent=running?'■':'🗑';queueMicrotask(renderActions);setTimeout(()=>void update(),100)}
});return button}
function renderActions(){if(detailId){const panel=document.querySelector('#detail .panelhead');if(!panel)return;let slot=document.getElementById('jobActionDetail');if(!slot){slot=document.createElement('span');slot.id='jobActionDetail';panel.append(slot)}const status=document.getElementById('status')?.textContent||'';if(status==='—')return;const mode=status==='RUNNING'||status==='QUEUED'?'stop':'delete';if(slot.firstChild?.classList.contains(mode)&&slot.firstChild.disabled===pending.has(detailId))return;slot.replaceChildren(action(detailId,status));return}
const table=document.querySelector('#index table');if(table&&!table.querySelector('th.job-action-head')){const th=document.createElement('th');th.className='job-action-head';th.textContent='Ação';table.querySelector('thead tr')?.append(th)}
for(const row of document.querySelectorAll('#jobs tr')){const link=row.querySelector('a[href*="/job/"]');if(!link)continue;const jobId=new RegExp('/job/([0-9a-f-]{36})','i').exec(link.getAttribute('href'))?.[1];if(!jobId)continue;const status=row.querySelector('.pill')?.textContent||'';let cell=row.querySelector('td.job-action-cell');if(!cell){cell=document.createElement('td');cell.className='job-action-cell';row.append(cell)}const mode=status==='RUNNING'||status==='QUEUED'?'stop':'delete';if(cell.firstChild?.classList.contains(mode)&&cell.firstChild.disabled===pending.has(jobId))continue;cell.replaceChildren(action(jobId,status))}
}
const target=detailId?document.getElementById('detail'):document.getElementById('index');new MutationObserver(renderActions).observe(target,{childList:true,subtree:true});renderActions();
})();
</script></body></html>`;
